# Generated by Django 3.1.6 on 2022-03-01 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Full', 'Full Area And Center'), ('Half', 'Half Area Left')], max_length=100)),
                ('image', models.ImageField(default='nomployee.png', upload_to='about')),
                ('facebook', models.CharField(default='https://www.facebook.com', max_length=255)),
                ('instagram', models.CharField(default='https://www.instagram.com', max_length=255)),
                ('twitter', models.CharField(default='https://twitter.com', max_length=255)),
                ('linkedin', models.CharField(default='https://www.linkedin.com', max_length=255)),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Company name (optional)')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField()),
                ('state', models.CharField(blank=True, max_length=30)),
                ('zip', models.CharField(max_length=30, verbose_name='Postal/Zip Code')),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('effective_delivery', models.CharField(choices=[('Office', 'Office'), ('Home', 'Home')], max_length=20, verbose_name='Select a label for effective delivery:')),
                ('order_notes', models.CharField(blank=True, max_length=255, verbose_name='Notes about your order (optional), e.g. special notes for delivery.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'addressbook',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('S', 'Shirt'), ('SP', 'Sport Wear'), ('OW', 'Out Wear')], max_length=2)),
                ('label', models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller')], max_length=2)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_menu', models.CharField(max_length=100)),
                ('short_detail', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(choices=[('Feature', 'Feature'), ('Menu', 'Menu'), ('Offer', 'Offer'), ('Discount', 'Discount')], default='Menu', max_length=30)),
                ('has_products', models.BooleanField(default=False, verbose_name='If yes, product will be show on this sub category, when product add to this category')),
                ('category_image', models.ImageField(default='noimage.png', upload_to='uploads')),
            ],
            options={
                'db_table': 'navigationmenu',
            },
        ),
        migrations.CreateModel(
            name='NavigationSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_menu', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('1', 'Menu'), ('0', 'Both Home and Menu')], default='1', max_length=2, verbose_name='For Menu, Both Home and Menu')),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_navbar', to='backend.navigationmenu')),
            ],
            options={
                'db_table': 'navigationsubmenu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('tracking_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('ordered', models.BooleanField(default=False)),
                ('option_options', models.TextField(blank=True, default=[], null=True)),
                ('checkout_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.addressbook')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50)),
                ('description', models.TextField(default='No Description')),
                ('display_in_navbar', models.BooleanField(default=False)),
                ('active_feature', models.CharField(default='New', max_length=20, verbose_name='Active Feature (show on top of product like BAG, )')),
                ('product_image', models.ImageField(default='noimage.png', upload_to='uploads')),
                ('has_discount', models.BooleanField(default=False)),
                ('discoun_price', models.FloatField(default=0)),
                ('display_in_home', models.BooleanField(default=False)),
                ('other_options', models.TextField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.navigationmenu')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_peoducts', to='backend.navigationsubmenu')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('facebook', models.CharField(default='https://www.facebook.com', max_length=200)),
                ('twitter', models.CharField(default='https://twitter.com', max_length=200)),
                ('instagram', models.CharField(default='https://instagram.com', max_length=200)),
                ('linkedin', models.CharField(default='https://www.linkedin.com', max_length=200)),
                ('pinterest', models.CharField(default='https://www.pinterest.com', max_length=200)),
                ('logo', models.ImageField(blank=True, default='noImage.png', upload_to='uploads')),
                ('slider_video_link', models.CharField(default='https://nfc.intelexcel.com/vid.mp4', max_length=255)),
                ('slider_type', models.IntegerField(choices=[(0, 'Video'), (1, 'Slided Images')], default=0)),
                ('theme_color', models.CharField(default='lightblue', max_length=10)),
            ],
            options={
                'db_table': 'sitesetting',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.products')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='uploads')),
                ('short_name', models.CharField(max_length=100, verbose_name='Short Appearance Name - like Seasion ETC')),
                ('short_Hesding', models.CharField(max_length=100, verbose_name='Short Detail, Headings ETC')),
                ('status', models.BooleanField(default=True, verbose_name='Active / Deactive')),
                ('explore_to', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.navigationsubmenu', verbose_name='User May Explore Related Products, Containing This Category')),
            ],
            options={
                'db_table': 'sliders',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('birthday', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('select', 'Drop Down')], max_length=20)),
                ('options', models.CharField(blank=True, max_length=255, verbose_name='Comma seperated values, options are only for (select type)')),
                ('sub_category', models.ManyToManyField(null=True, to='backend.NavigationSubMenu', verbose_name='Please Select Sub Category, The option option will apply in')),
            ],
            options={
                'db_table': 'productoption',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
                ('color', models.CharField(max_length=50)),
                ('display_place', models.CharField(choices=[('0', 'Regular Image'), ('1', 'Descriptive Image')], default='0', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_images', to='backend.products')),
            ],
            options={
                'db_table': 'productsimages',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Succeeded', 'Succeeded'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], max_length=50)),
                ('deliverd_date', models.DateTimeField()),
                ('orderid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
            ],
            options={
                'db_table': 'orderstatus',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orderitem',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='backend.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkoutaddress',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('display_on', models.CharField(choices=[('Top', 'Top in Slider Section'), ('Down', 'Down in Card Section')], max_length=10)),
                ('image', models.ImageField(upload_to='blogs')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('in_products', models.ManyToManyField(to='backend.Products', verbose_name='Select List of products')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.navigationsubmenu')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
