# Generated by Django 3.1.6 on 2022-03-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsubmenu',
            name='sub_menu_slug',
            field=models.SlugField(default='None', null=True),
        ),
    ]
