# Generated by Django 3.1.6 on 2022-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_navigationsubmenu_sub_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsubmenu',
            name='sub_menu',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='navigationsubmenu',
            name='sub_menu_slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
