# Generated by Django 3.1.6 on 2022-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220304_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='checkoutaddress',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='navigationmenu',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='navigationsubmenu',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sliders',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='products',
            name='product_slug_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='navigationsubmenu',
            name='sub_menu_slug',
            field=models.SlugField(blank=True, default='', null=True, verbose_name='Sub menu slug (leave blank will auto fill.)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discoun_price',
            field=models.FloatField(default=0, verbose_name='minus discount from total price'),
        ),
    ]
