# Generated by Django 3.1.6 on 2022-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220311_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('stars', models.IntegerField()),
                ('type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='terms_and_condion',
            field=models.TextField(blank=True, default='A liability disclaimer is a statement from your business that denies responsibility for damages that your visitors may suffer as a result of using your service.'),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='effective_delivery',
            field=models.CharField(choices=[('Office', 'Office'), ('Home', 'Home')], max_length=20, verbose_name='effective delivery:'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='type',
            field=models.CharField(choices=[('text', 'Display as text'), ('color', 'Display as color')], max_length=20),
        ),
    ]
