# Generated by Django 3.1.6 on 2022-03-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220312_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='display_on',
        ),
    ]
