# Generated by Django 3.1.6 on 2022-03-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_blog_display_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='working_hours',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Size (also use for filter)'),
        ),
    ]
