# Generated by Django 3.1.6 on 2022-03-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_navigationsubmenu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsubmenu',
            name='icon',
            field=models.CharField(blank=True, default='noicon', max_length=255),
        ),
        migrations.CreateModel(
            name='SeasionSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.navigationsubmenu', verbose_name='Product Category sales in?')),
            ],
            options={
                'db_table': 'seasionsale',
            },
        ),
    ]
