# Generated by Django 3.1.6 on 2022-03-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20220325_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationmenu',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='navigationmenu',
            name='location',
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='icon',
            field=models.CharField(blank=True, default='noicon', max_length=255),
        ),
        migrations.AlterField(
            model_name='navigationmenu',
            name='has_products',
            field=models.BooleanField(default=False, verbose_name='If yes, product will be display in home page in our products section.'),
        ),
    ]
