# Generated by Django 3.1.6 on 2022-03-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='discount_banner',
            field=models.ImageField(default='noimage.png', upload_to='discount_banner'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='should_display_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='image',
            field=models.ImageField(upload_to='instagram'),
        ),
    ]
