# Generated by Django 3.1.6 on 2022-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20220330_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='background_header_footer_color',
            field=models.CharField(default='lightblue', max_length=10),
        ),
    ]
