# Generated by Django 3.1.6 on 2022-04-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_sitesetting_background_header_footer_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs', verbose_name='Image (1440 × 1440 px)'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='image',
            field=models.ImageField(upload_to='instagram', verbose_name='Image (223 × 223 px)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='noimage.png', upload_to='uploads', verbose_name='Product Image (420 × 315 px)'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='seasionsale',
            name='image',
            field=models.ImageField(upload_to='uploads', verbose_name='Image (420 × 315 px)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='discount_banner',
            field=models.ImageField(default='noimage.png', upload_to='discount_banner', verbose_name='Home discount banner (1139 × 76 px)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='uploads', verbose_name='Logo (141 × 50 px)'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='slider_image',
            field=models.ImageField(upload_to='uploads', verbose_name='Slider Image (1500 × 1000 px)'),
        ),
    ]
