# Generated by Django 3.1.6 on 2022-04-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rating_answer_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
    ]
