# Generated by Django 3.1.6 on 2022-04-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rating_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='product_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.products'),
        ),
    ]
