# Generated by Django 3.1.6 on 2022-04-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20220409_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='background_header_footer_color',
        ),
    ]
