# Generated by Django 3.1.6 on 2022-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_sitesetting_background_header_footer_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='blog_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Blog page head image (1920 × 300 px)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='login_page_side_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='orders_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Home discount banner (1920 × 300 px)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='payment_delivery_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Payment delivery page head image (1920 × 300 px)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='product_detail_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Product detail page head image (1920 × 300 px)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='product_list_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Product list page head image (1920 × 300 px)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='receipt_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Home discount banner (1920 × 300 px)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='trackeing_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Home discount banner (1920 × 300 px)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='view_cart_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='View cart page head image (1920 × 300 px)'),
        ),
    ]
