# Generated by Django 3.1.6 on 2022-04-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20220409_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='text_color',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='login_background_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Login background image (1920 × 1100 px)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='nav_text_color',
            field=models.CharField(default='lightblue', max_length=10, verbose_name='Nav and footer text color'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='orders_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Orders page head image (1920 × 300 px)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='receipt_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Receipt page head image (1920 × 300 px)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='trackeing_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Trackeing page head image (1920 × 300 px)'),
        ),
    ]
