# Generated by Django 3.1.6 on 2022-04-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20220409_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='theme_background_color_1',
            field=models.CharField(default='#56CCF2', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='theme_background_color_2',
            field=models.CharField(default='#2F80ED', max_length=10),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Product Image (640, 480 px)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='noimage.png', upload_to='uploads', verbose_name='Product Image (640, 480 px)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, default='noImage.png', upload_to='uploads', verbose_name='Logo (150 × 150 px)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='payment_delivery_page_head_image',
            field=models.ImageField(default='noimage.png', upload_to='page_headings', verbose_name='Payment delivery (checkout) page head image  (1920 × 300 px)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='theme_color',
            field=models.CharField(default='#1e90ff', max_length=10, verbose_name='Theme text colors'),
        ),
    ]
