# Generated by Django 3.1.6 on 2022-04-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20220418_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_colrs',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='defins colors in comma seperated'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_sizes',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='defins sizes in comma seperated'),
        ),
    ]
