# Generated by Django 3.1.6 on 2022-04-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20220418_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_colrs',
            new_name='product_colors',
        ),
    ]
