# Generated by Django 3.1.6 on 2022-04-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20220418_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='option_options',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_with_price',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
