# Generated by Django 3.1.6 on 2022-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20220419_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='back_cushions',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_product_has_back_cushions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='product_back_cushions',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='defins back cushions in comma seperated'),
        ),
    ]
