# Generated by Django 3.1.6 on 2022-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20220423_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='theme',
            field=models.CharField(choices=[('1', 'Theme 1'), ('2', 'Theme 2')], default='1', max_length=2),
        ),
    ]
