# Generated by Django 3.1.6 on 2022-05-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_sitesetting_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dimension',
            field=models.TextField(default='No Dimension'),
        ),
    ]
